language: cpp
compiler:
  - clang
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libboost1.48-all-dev protobuf-compiler libprotobuf-dev libssl-dev exuberant-ctags scons
script: scons && npm install && npm test
notifications:
  email:
    false
  irc:
    channels:
      - "chat.freenode.net#ripple-dev"
